version: '3.9'
services:
  database:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=${TODO_APP_DB_USER}
      - POSTGRES_PASSWORD=${TODO_APP_DB_PASSWORD}
      - POSTGRES_DB=${TODO_APP_DB_DATABASE}
    ports:
      - '${TODO_APP_DB_PORT}:5432'
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
